"""add media fields to questions

Revision ID: 30a7c4691ef6
Revises: a1b2c3d4e5f6
Create Date: 2026-03-12 22:04:50.709028+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30a7c4691ef6"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_game_sessions_room_id"), "game_sessions", type_="unique"
    )
    op.add_column(
        "questions",
        sa.Column("media_type", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("telegram_file_id", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "telegram_file_id")
    op.drop_column("questions", "media_type")
    op.create_unique_constraint(
        op.f("uq_game_sessions_room_id"),
        "game_sessions",
        ["room_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
