"""add is_private to game_sessions

Revision ID: 2026_03_16_abc123456789
Revises: 81d9380ae384
Create Date: 2026-03-16 00:00:00.000000+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2026_03_16_abc123456789"
down_revision: Union[str, None] = "81d9380ae384"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_sessions",
        sa.Column("is_private", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_sessions", "is_private")
    # ### end Alembic commands ###
